# Generated by Django 2.2.4 on 2020-04-12 09:50

from django.db import migrations


def fill_flats_to_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.owner,
                                    owners_phonenumber=owner.owners_phonenumber,
                                    owner_phone_pure=owner.owner_phone_pure,)
        owner.flats.add(*flats)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.flats.through.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20200412_1248'),
    ]

    operations = [
        migrations.RunPython(fill_flats_to_owner_model, move_backward)
    ]
